# Generated by Django 5.2.15 on 2026-07-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=300)),
                ('about', models.TextField()),
                ('venue', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('conference_start', models.DateField()),
                ('conference_end', models.DateField()),
                ('hero_background', models.ImageField(upload_to='hero/')),
                ('logo_left', models.ImageField(upload_to='logo/')),
                ('logo_right', models.ImageField(upload_to='logo/')),
                ('registration_link', models.CharField(max_length=300)),
                ('paper_submission_link', models.CharField(max_length=300)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('copyright', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Conference Settings',
            },
        ),
    ]
