# Generated by Django 5.2.15 on 2026-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conferencesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='ConferenceSettings',
        ),
    ]
