# Generated by Django 5.2.15 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_statistics_delete_conferencesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment/')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('payment_instructions', models.TextField(blank=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Research Scholar', 'Research Scholar'), ('Faculty', 'Faculty'), ('Industry', 'Industry')], max_length=50, unique=True)),
                ('indian_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foreign_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
