# Generated by Django 5.2.15 on 2026-06-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersubmission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
    ]
