# Generated by Django 5.2.15 on 2026-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_paymentsettings_registrationfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsettings',
            old_name='payment_instructions',
            new_name='payment_note',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='support_phone',
        ),
        migrations.RemoveField(
            model_name='registrationfee',
            name='description',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='camera_ready_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='organization',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationfee',
            name='foreign_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrationfee',
            name='indian_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
