# Generated by Django 5.2.15 on 2026-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='conference_banner/')),
            ],
        ),
    ]
