# Generated by Django 5.2.15 on 2026-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_conferencetrack_contactmessage_gallery_venuelocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('send_email', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
