# Generated by Django 5.2.15 on 2026-06-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_broadcastmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='send_sms',
        ),
    ]
