# Generated by Django 5.2.15 on 2026-06-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_remove_broadcastmessage_send_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
